/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AtomButton: typeof import('./src/components/atom/AtomButton.vue')['default']
    AtomInput: typeof import('./src/components/atom/AtomInput.vue')['default']
    CommonLayout: typeof import('./src/components/layout/CommonLayout.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    InputForm: typeof import('./src/components/molecules/InputForm.vue')['default']
  }
}
